drop database if exists editorial;
-- MySQL Script generated by MySQL Workbench
-- Fri Dec 30 03:08:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Editorial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Editorial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Editorial` DEFAULT CHARACTER SET utf8 ;
USE `Editorial` ;

-- -----------------------------------------------------
-- Table `Editorial`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Autor` (
  `cedula_Autor` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NULL,
  `Dirección` VARCHAR(100) NOT NULL,
  `Correo` VARCHAR(128) NULL,
  `fecha_Nacimiento` DATE NOT NULL,
  PRIMARY KEY (`cedula_Autor`));


-- -----------------------------------------------------
-- Table `Editorial`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Articulo` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `Descripción` VARCHAR(100) NULL,
  PRIMARY KEY (`idArticulo`));


-- -----------------------------------------------------
-- Table `Editorial`.`Editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Editor` (
  `cedula_Editor` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `fecha_Nacimiento` DATE NOT NULL,
  `Salario` DECIMAL NOT NULL DEFAULT 450.00,
  `Correo` VARCHAR(128) NULL,
  `tipoCargo` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NULL,
  PRIMARY KEY (`cedula_Editor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`RevistaInicial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`RevistaInicial` (
  `idRevistaInicial` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRevistaInicial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`Aprobación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Aprobación` (
  `idAprobacion` INT NOT NULL AUTO_INCREMENT,
  `cedula_Editor` VARCHAR(10) NOT NULL,
  `idArticulo` INT NOT NULL,
  `SecciónPublicar` VARCHAR(45) NOT NULL,
  `Estado` TINYINT NULL,
  `Aprobacióncol` VARCHAR(45) NULL,
  `idRegistroRevista` INT NOT NULL,
  PRIMARY KEY (`idAprobacion`, `cedula_Editor`, `idArticulo`, `idRegistroRevista`),
  INDEX `fk_Aprobación_Editor1_idx` (`cedula_Editor` ASC) VISIBLE,
  INDEX `fk_Aprobación_Articulo1_idx` (`idArticulo` ASC) VISIBLE,
  INDEX `fk_Aprobación_Revista1_idx` (`idRegistroRevista` ASC) VISIBLE,
  CONSTRAINT `fk_Aprobación_Editor1`
    FOREIGN KEY (`cedula_Editor`)
    REFERENCES `Editorial`.`Editor` (`cedula_Editor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aprobación_Articulo1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `Editorial`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aprobación_Revista1`
    FOREIGN KEY (`idRegistroRevista`)
    REFERENCES `Editorial`.`RevistaInicial` (`idRevistaInicial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`Historial Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Historial Articulo` (
  `idHistorial Articulo` INT NOT NULL AUTO_INCREMENT,
  `idArticulo` INT NOT NULL,
  `Comentario` VARCHAR(200) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`idHistorial Articulo`, `idArticulo`),
  INDEX `fk_Historial Articulo_Articulo1_idx` (`idArticulo` ASC) VISIBLE,
  CONSTRAINT `fk_Historial Articulo_Articulo1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `Editorial`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`Escribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Escribe` (
  `cedula_Autor` VARCHAR(10) NOT NULL,
  `idArticulo` INT NOT NULL,
  PRIMARY KEY (`cedula_Autor`, `idArticulo`),
  INDEX `fk_Escribe_Articulo1_idx` (`idArticulo` ASC) VISIBLE,
  CONSTRAINT `fk_Escribe_Autor1`
    FOREIGN KEY (`cedula_Autor`)
    REFERENCES `Editorial`.`Autor` (`cedula_Autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Escribe_Articulo1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `Editorial`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`Maquetacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Maquetacion` (
  `idMaquetacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_Inicio` DATE NOT NULL,
  `fecha_Fin` DATE NOT NULL,
  `Comentario` VARCHAR(250) NULL,
  `idRevistaInicial` INT NOT NULL,
  PRIMARY KEY (`idMaquetacion`, `idRevistaInicial`),
  INDEX `fk_Maquetación_Revista1_idx` (`idRevistaInicial` ASC) VISIBLE,
  CONSTRAINT `fk_Maquetación_Revista1`
    FOREIGN KEY (`idRevistaInicial`)
    REFERENCES `Editorial`.`RevistaInicial` (`idRevistaInicial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`Diseñador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Diseñador` (
  `cedula_Autor` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NULL,
  `Dirección` VARCHAR(100) NOT NULL,
  `Correo` VARCHAR(128) NULL,
  `fecha_Nacimiento` DATE NOT NULL,
  PRIMARY KEY (`cedula_Autor`));


-- -----------------------------------------------------
-- Table `Editorial`.`Diseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Diseña` (
  `cedula_Autor` VARCHAR(10) NOT NULL,
  `idMaquetación` INT NOT NULL,
  PRIMARY KEY (`cedula_Autor`, `idMaquetación`),
  INDEX `fk_Diseñan_Maquetación1_idx` (`idMaquetación` ASC) VISIBLE,
  CONSTRAINT `fk_Diseñan_Diseñador1`
    FOREIGN KEY (`cedula_Autor`)
    REFERENCES `Editorial`.`Diseñador` (`cedula_Autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseñan_Maquetación1`
    FOREIGN KEY (`idMaquetación`)
    REFERENCES `Editorial`.`Maquetacion` (`idMaquetacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`RevistaFinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`RevistaFinal` (
  `idRevistaFinal` INT NOT NULL AUTO_INCREMENT,
  `idMaquetación` INT NOT NULL,
  `idRevistaInicial` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idRevistaFinal`, `idMaquetación`, `idRevistaInicial`),
  INDEX `fk_RevistaFinal_Maquetación1_idx` (`idMaquetación` ASC) VISIBLE,
  INDEX `fk_RevistaFinal_RevistaInicial1_idx` (`idRevistaInicial` ASC) VISIBLE,
  CONSTRAINT `fk_RevistaFinal_Maquetación1`
    FOREIGN KEY (`idMaquetación`)
    REFERENCES `Editorial`.`Maquetacion` (`idMaquetacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RevistaFinal_RevistaInicial1`
    FOREIGN KEY (`idRevistaInicial`)
    REFERENCES `Editorial`.`RevistaInicial` (`idRevistaInicial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Editorial`.`Publicación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editorial`.`Publicación` (
  `idPublicación` INT NOT NULL AUTO_INCREMENT,
  `fechaPublicacion` DATE NOT NULL,
  `Sección` VARCHAR(45) NULL,
  `idRevistaFinal` INT NOT NULL,
  PRIMARY KEY (`idPublicación`, `idRevistaFinal`),
  UNIQUE INDEX `Sección_UNIQUE` (`Sección` ASC) VISIBLE,
  INDEX `fk_Publicación_RevistaFinal1_idx` (`idRevistaFinal` ASC) VISIBLE,
  CONSTRAINT `fk_Publicación_RevistaFinal1`
    FOREIGN KEY (`idRevistaFinal`)
    REFERENCES `Editorial`.`RevistaFinal` (`idRevistaFinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
